---
# handlers file for ansible-role-tCoffee

- name: Remove biol tmp dir
  file:
    state: absent
    path: "/tmp/biol/"


- name: Remove environment activation in .bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "^conda activate bl_*"
    state: absent